apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-snippetbox
    labels:
        app: go-snippetbox
spec:
    replicas: 1
    selector:
        matchLabels:
            app: go-snippetbox
    template:
        metadata:
            labels:
                app: go-snippetbox
        spec:
            containers:
            - name: go-snippetbox
              image: jthrone/go-snippetbox
              imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 80
            env:
            - name: MYSQL_DATABASE_HOST
              value: 10.97.28.50
            - name: MYSQL_DATABASE_NAME
              value: snippetbox
            - name: MYSQL_USERNAME
              valueFrom:
                  secretKeyRef:
                      name: mysql-secret
                      key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: mysql-secret
                      key: mysql-password

