apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-snippetbox
    labels:
        app: go-snippetbox
spec:
    replicas: 1
    selector:
        matchLabels:
            app: go-snippetbox
    template:
        metadata:
            labels:
                app: go-snippetbox
        spec:
            containers:
            - name: go-snippetbox
              image: jthrone/go-snippetbox
              imagePullPolicy: Always
              ports:
              - containerPort: 80
              env:
              - name: MYSQL_DATABASE_HOST
                valueFrom:
                    configMapKeyRef:
                        name: mysql-configmap
                        key: database-url
              - name: MYSQL_DATABASE_NAME
                value: snippetbox
              - name: MYSQL_USERNAME
                valueFrom:
                    secretKeyRef:
                        name: mysql-secret
                        key: mysql-username
              - name: MYSQL_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: mysql-secret
                        key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
    name: go-snippetbox-service
spec:
    selector:
        app: go-snippetbox
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30000

