apiVersion: apps/v1
kind: Deployment
metadata:
    name: snippetbox-go
    labels:
        app: snippetbox-go
spec:
    replicas: 1
    selector:
        matchLabels:
            app: snippetbox-go
    template:
        metadata:
            labels:
                app: snippetbox-go
        spec:
            containers:
            - name: snippetbox-go
              image: jthrone/snippetbox-go:0.0.9
              imagePullPolicy: Always
              ports:
              - containerPort: 80
              env:
              - name: MYSQL_DATABASE_HOST
                valueFrom:
                    configMapKeyRef:
                        name: mysql-configmap
                        key: database-url
              - name: MYSQL_DATABASE_NAME
                value: "snippetbox"
              - name: MYSQL_DATABASE_PORT
                value: "3306"
              - name: APP_PORT
                value: "80"
              - name: MYSQL_USERNAME
                valueFrom:
                    secretKeyRef:
                        name: mysql-secret
                        key: mysql-username
              - name: MYSQL_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: mysql-secret
                        key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
    name: snippetbox-go-service
spec:
    selector:
        app: snippetbox-go
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30000

